name: flutter_web_service
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  http: ^1.2.2
  path_provider: ^2.0.15
  xml: ^6.5.0
  google_maps_flutter: ^2.2.1
  intl: ^0.20.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - images/
